# Generated by Django 5.0.1 on 2024-02-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('diagnose', models.CharField(max_length=30)),
                ('had_surgery', models.BooleanField()),
                ('herb8_info', models.CharField(max_length=50)),
            ],
        ),
    ]
