# Generated by Django 5.0.1 on 2024-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb8terapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha')], max_length=10, null=True)),
                ('marital_status', models.CharField(choices=[('Menikah', 'Menikah'), ('Belum Menikah', 'Belum Menikah')], max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('diagnose', models.CharField(blank=True, max_length=100, null=True)),
                ('had_surgery', models.BooleanField(blank=True, null=True)),
                ('herb8_info', models.IntegerField(blank=True, choices=[(0, 'Keluarga / Teman'), (1, 'Brosur / Koran'), (2, 'Spanduk / Baliho'), (3, 'Facebook'), (4, 'Instagram'), (5, 'Lainnya')], null=True)),
            ],
        ),
    ]
