# Generated by Django 5.0.1 on 2024-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb8terapi', '0004_registration_rand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=9),
        ),
        migrations.AlterField(
            model_name='registration',
            name='herb8_info',
            field=models.IntegerField(blank=True, choices=[('Keluarga / Teman', 'Keluarga / Teman'), ('Brosur / Koran', 'Brosur / Koran'), ('Spanduk / Baliho', 'Spanduk / Baliho'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Lainnya', 'Lainnya')], null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='rand_id',
            field=models.CharField(max_length=16),
        ),
    ]
