# Generated by Django 5.0.1 on 2024-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb8terapi', '0005_alter_registration_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='herb8_info',
            field=models.CharField(blank=True, choices=[('Keluarga / Teman', 'Keluarga / Teman'), ('Brosur / Koran', 'Brosur / Koran'), ('Spanduk / Baliho', 'Spanduk / Baliho'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Lainnya', 'Lainnya')], max_length=50, null=True),
        ),
    ]
